Feature: Arabic to Romanian Converter
  Scenario Outline: Converting an Arabic numerals to Romanian
    Given I have a numerals converter
    When I convert <arabic> to Romanina numeral
    Then I should get <romanian>
    Examples:
      | arabic | romanian                                                                                                                                                                                                                                                                                                                                                          |
      | 1      | "I"                                                                                                                                                                                                                                                                                                                                                               |
      | 20     | "XX"                                                                                                                                                                                                                                                                                                                                                              |
      | 35     | "XXXV"                                                                                                                                                                                                                                                                                                                                                            |
      | 5754   | "MMMMMDCCLIV"                                                                                                                                                                                                                                                                                                                                                     |
      | 542    | "DXLII"                                                                                                                                                                                                                                                                                                                                                           |
      | 1988   | "MCMLXXXVIII"                                                                                                                                                                                                                                                                                                                                                     |
      | 345635 | "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDCXXXV" |
      | 843    | "DCCCXLIII"                                                                                                                                                                                                                                                                                                                                                       |

